---
spring:
  profiles:
    active: dev
  application:
    name: notification-service
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgres://kbjlrqic:jg0vLGmuQ27kAp_BwvgK422x9o3G48bh@stampy.db.elephantsql.com:5432/kbjlrqic
    username: kbjlrqic
    password: '{cipher}3451b6c9ce5bd91082afc85b681eef108131ba87e6c5aacc2c4e1ce516ba320b63c2aacc0319af8ff528ceee8fa03f60c6dd2cf912dbbbb8978126469af58152'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  cache:
    type: redis
  redis:
    host: redis-13519.c16.us-east-1-2.ec2.cloud.redislabs.com
    port: 13519
#   rabbitmq:
#     addresses: amqp://awiymfbp:wBVmFlXLDtOtMgIWZk4qHftJKT1QPVGV@baboon.rmq.cloudamqp.com/awiymfbp
  rabbitmq:
    host: baboon.rmq.cloudamqp.com
    port: 5672
    username: awiymfbp
    password: '{cipher}d79846483197fd363d4b82608ffc8785db279b50a9dd4babba57c563acb7f8312cfcd40eb6c9cedf739d6e4d6ab1437cd01344a49ec6e2220e72e9620a1e6c3e'
  cloud:
    config:
      profile: dev
    bus:
      #Workaround for defect in https://github.com/spring-cloud/spring-cloud-bus/issues/124
      id: ${vcap.application.name:${spring.application.name:application}}:${vcap.application.instance_index:${spring.profiles.active:${local.server.port:${server.port:0}}}}
custom:
  featureSwitch:
    userApiEnabled: false
    

security:
  basic:
    enabled: false
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
