eureka:
  instance:
#     hostname: ${spring.application.name}-g.herokuapp.com
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: https://user:${EUREKA_USER_PASSWORD:password}@${EUREKA_HOST:eureka-server-g}.herokuapp.com/eureka/

# server:
#   port: ${random.int[8080,8090]}

security:
  basic:
    enabled: false
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
