---
spring:
  application:
    name: product-service
  profiles: local
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/products-service-db
    username: postgres
    password: '{cipher}b65ccba0cc2851fe90b46e2c2b7488a21762ecf811eec53c9215770483313397'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: create

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
