---
spring:
  application:
    name: galaxy-game-service
  profiles: dev
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-50-19-109-120.compute-1.amazonaws.com:5432/dbrospqj2lg425
    username: nrroddpwdzwbjc
    password: '{cipher}5a532612920a78497a0fbc7bbe6662e563d596774cdb224bca5b01efcdc10149b7f1b844c8ca078937f139e0968c13e42c08cb1945a18351a86fe1c211c7e909486777b20b579d4f06d90034a94a0ad5d1e2e42ef830b5059347c10993254784'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  cache:
    type: redis
  redis:
    host: redis-15348.c9.us-east-1-4.ec2.cloud.redislabs.com
    port: 15348
    password: '{cipher}10c2a8ff30393e0306f3abb39f351910738cb66058ed37f414a2c9d181f5fde30df688fa9eb33a083c76df5e6c49ba5421646e32f272b73e58cfab283ae34a82'
    time-to-live: 600000
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
amazonProperties:
  endpointUrl: https://s3.us-east-2.amazonaws.com
  accessKey: XXXXXXXXXXXXXXXXX
  secretKey: XXXXXXXXXXXXXXXXXXXXXXXXXX
  bucketName: your-bucket-name
