---
spring:
  application:
    name: user-service
  profiles: dev
  datasource:
    driverClassName: org.postgresql.Driver
    url: postgres://ec2-23-23-173-30.compute-1.amazonaws.com:5432/db7ts55aogrd7n
    username: cbzvzjkunzmtwn
    password: '{cipher}698fcc99eb73d5e4d3de29ba03b854d645a12a6182402b2307eca1345981a1e8ad6a7bcc7b779b0f124d1a798f5d1f0ca5299077d8051a89dcdb72187bd4b6805870a55371397fa22979d4611e12bed8282408e590d66f4494a1ef20cca420e4'
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
    time-to-live: 600000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: '{cipher}2462bc5b9ec8ed174d1b1ace79e64632762d4e85490f0f067f116bdec6db9892'
