---
spring:
  application:
    name: user-service
  profiles: dev
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://ec2-23-23-173-30.compute-1.amazonaws.com:5432/db7ts55aogrd7n
    username: cbzvzjkunzmtwn
    password: 7bf571dd1c804b9a1d4b5945968e689fc8ee9134e11225791d0c6baa02bb70a0
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate.ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  cache:
    type: redis
  redis:
    host: redis-17446.c114.us-east-1-4.ec2.cloud.redislabs.com
    port: 17446
    password: '{cipher}2cdc744ee96a56fb81bebb2e1a84ffdec4ee5194e95762ec5302bc20fe119aaeed080d546196fc0cd0b3c6f7721270c130add742b508719a4c43772131b2ceaa'
    time-to-live: 600000
  rabbitmq:
    host: zebra.rmq.cloudamqp.com
    username: llhodgzs
    password: '{cipher}a1da1726d270da1cabe19e14340c453b429102f956f997bf5274b340dabaf997b22d00a2a6b8d5818dadc615a11389665be244446bcfa1eeb1eb41e0fc025625'
