---
spring:
  application:
    name: gateway-service
zuul:
  routes:
    user-service:
      path: /user-service/**
      sensitive-headers: Cookie,Set-Cookie
    reservation-service:
      path: /reservation-service/**
      sensitive-headers: Set-Cookie,Authorization
    product-service:
      path: /product-service/**
      sensitive-headers: Set-Cookie,Authorization
    relationship-service:
      path: /relationship-service/**
      sensitive-headers: Set-Cookie,Authorization
    eureka:
      path: /eureka/**
      sensitive-headers: Set-Cookie,Authorization
      url: https://user:${EUREKA_USER_PASSWORD:password}@${EUREKA_HOST:eureka-server-g}.herokuapp.com
    auth-service:
      path: /auth/**
      strip-prefix: false
      sensitive-headers: Cookie,Set-Cookie # Exclude authorization from sensitive headers
